# Site Settings
title: My Resume
url: 'https://meysubb.github.io/'
baseurl: '/online-resume' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Meyappan Subbaiah
tagline: Business Analytics Student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Current Business Analytics graduate student at the McCombs School of Business at the University of Texas. '

#sidebar links
email: meysubb@gmail.com
phone:
website: meysubb.github.io #do not add http://
linkedin: msubbaiah
github: meysubb
twitter:
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
